name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout репозитория
      uses: actions/checkout@v4

    - name: Установка зависимостей
      run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev

    - name: Сборка тестов
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Запуск тестов
      run: ./build/test_runner
